try
    purge
end


[cDirThis, cName, cExt] = fileparts(mfilename('fullpath'));
cDirMic = fullfile(cDirThis, '..', 'src');
addpath(genpath(cDirMic));


clock = mic.Clock('Master');

uiA = mic.ui.device.GetSetNumber('clock', clock, 'cName', 'A', 'cLabel', 'A');
uiB = mic.ui.device.GetSetNumber('clock', clock, 'cName', 'B', 'cLabel', 'B');
uiC = mic.ui.device.GetSetNumber('clock', clock, 'cName', 'C', 'cLabel', 'C');
uiD = mic.ui.device.GetSetNumber('clock', clock, 'cName', 'D', 'cLabel', 'D');


% Create a list of three states

%{
states = {...
    mic.StateFromUiGetSetNumber(uiA, 5, 0.1, uiA.getUnit().name), ...
    mic.StateFromUiGetSetNumber(uiB, 100, 0.1, uiB.getUnit().name) ...
    mic.StateFromUiGetSetNumber(uiC, 20, 0.1, uiC.getUnit().name) ...
};
%}


% Alternatively (DOES NOT WORK, can't get lambda working in Static


states = {...
    mic.State.fromUiGetSetNumber(uiA, 5, 0.1, uiA.getUnit().name), ...
    mic.State.fromUiGetSetNumber(uiB, 100, 0.1, uiB.getUnit().name) ...
    mic.State.fromUiGetSetNumber(uiC, 20, 0.1, uiC.getUnit().name) ...
};



% This sequence is itself a "state" since it implements mic.interface.State
% Uses mic.Scan under the hood to implement go()
state = mic.StateSequence(...
    'clock', clock, ...
    'ceStates', states, ...
    'dPeriod', 0.5, ...
    'cName', 'ABC Scan', ...
    'fhGetMessageThere', 'ABC In Position', ...
    'fhGetMessageNotThere', 'ABC Not In Position', ...
    'fhGetMessageMoving', 'ABC Moving ...' ...
);


% state.go();


state2 = mic.StateSequence(...
    'clock', clock, ...
    'ceStates', {...
        mic.State.fromUiGetSetNumber(uiD, 30, 0.1, uiD.getUnit().name), ...
        state ...
    }, ...
    'dPeriod', 0.5, ...
    'fhGetMessageThere', 'ABCD In Position', ...
    'fhGetMessageNotThere', 'ABCD Not In Position', ...
    'fhGetMessageMoving', 'ABCD Moving ...', ...
    'cName', 'ABCD Scan' ...
);


h = figure;
uiA.build(h, 10, 10);
uiB.build(h, 10, 50);
uiC.build(h, 10, 100);
uiD.build(h, 10, 200);


uiButtonABC = mic.ui.common.ActiveButton(...
    'clock', clock, ...
    'cName', 'state-abc-test', ...
    'fhOnClick', @() state.go(), ...
    'fhGetColor', @() state.getColor(), ...
    'fhGetText', @() state.getMessage() ...
);


uiButtonABCD = mic.ui.common.ActiveButton(...
    'clock', clock, ...
    'cName', 'state-abcd-test', ...
    'fhOnClick', @() state2.go(), ...
    'fhGetColor', @() state2.getColor(), ...
    'fhGetText', @() state2.getMessage() ...
);

uiButtonABC.build(h, 10, 250, 200, 30);
uiButtonABCD.build(h, 10, 280, 200, 30);

